# This is the configuration for pre-commit, a local framework for managing pre-commit hooks
#   Check out the docs at: https://pre-commit.com/

default_stages: [commit]
repos:
  - repo: https://github.com/shssoichiro/oxipng
    rev: v8.0.0
    hooks:
      - id: oxipng
        stages: [manual]
